[development]
rebuild_before_running = true
enable_rebuild_indicator = true

[workspace]
paths = ["$HOME/projects", "$HOME/personal", "$HOME/Documents", "$HOME/"]

[memories]
path = "$HOME/personal/grimoire/memories/"

[system]
rpms_path = "$HOME/rpms"
packages = '''
keepassxc
git
stow
delta
nix
dnf-command(versionlock)
zsh
oh-my-posh
keychain
fzf
zoxide
ghostty
eza
golang
gcc
clang
tmux
tree-sitter-cli
fastfetch
find
fd
gopls
golang-mvdan-gofumpt
rg
gimp
bat
bc
btop
dua
sqlite
unzip
gitleaks
hyperfine
vesktop-1.6.5.x86_64.rpm
qdbus
loupe
chromium
stylua
caddy

# ZFS
@RAW https://zfsonlinux.org/fedora/zfs-release-3-1$(rpm --eval "%{dist}").noarch.rpm
@RAW kernel-devel-$(uname -r | awk -F'-' '{print $1}')
# NOTE: zfs must be after kernel was installed (as 2 separate k sync!!!!)
zfs

# For webzfs
libsodium-devel libffi-devel python3-devel

# For sanoid/syncoid
perl-Config-IniFiles perl-Data-Dumper perl-Capture-Tiny perl-Getopt-Long lzop mbuffer mhash pv

'''

[system.copr]
"scottames/ghostty" = {}
"yorickpeterse/stylua" = {}

# sudo dnf install ./path/to/package.rpm
# rpm -qp ./path/to/package.rpm
# sudo dnf remove package-name
