[development]
rebuild_before_running = true
enable_rebuild_indicator = true

[workspace]
paths = ["$HOME/projects", "$HOME/personal", "$HOME/Documents", "$HOME/"]

[memories]
path = "$HOME/personal/grimoire/memories/"

[system]
rpms_path = "$HOME/rpms"

copr = '''
scottames/ghostty
yorickpeterse/stylua
quadratech188/vicinae
ilyaz/LACT
g3tchoo/prismlauncher
'''

packages = '''
keepassxc
git
stow
delta
nix
dnf-command(versionlock)
zsh
oh-my-posh
keychain
fzf
zoxide
ghostty
eza
golang gopls
gcc clang lld mold gdb lldb nasm clangd
tmux
tree-sitter-cli
fastfetch
find
fd
golang-mvdan-gofumpt
rg
krita gimp inkscape
drawio-x86_64-30.0.4.rpm
bat
bc
btop
dua
unrar
sqlite
unzip
gitleaks
hyperfine # For benchmarking
vesktop-1.6.5.x86_64.rpm
qdbus
loupe
chromium
stylua
caddy
etckeeper
vicinae
cargo
python3-pip
pnpm nodejs
java-openjdk-headless java-25-openjdk-devel
filezilla
jq
kate
gh
libreoffice
yt-dlp mpv
xlsclients xwininfo
nodejs-bash-language-server
fuse-libs # For AppImages to work
openrgb
kdelibs-webkit
qdirstat # WizTree for linux
tokei
piper # Uses ratbagd under the hood
pipewire-codec-aptx # Bluetooth codec, probably not needed but why not (oh, this was already installed)
obs-studio-plugin-vkcapture

# Gaming
steam lutris Heroic-2.22.0-linux-x86_64.rpm
mangohud gamemode gamescope
r2modman-3.2.17.x86_64.rpm
wine winetricks protontricks
prismlauncher

# AMD Control/Monitoring tools
corectrl lact radeontop amdgpu_top-0.11.5-1.x86_64.rpm

# ZFS
@RAW https://zfsonlinux.org/fedora/zfs-release-3-1$(rpm --eval "%{dist}").noarch.rpm
@RAW kernel-devel-$(uname -r | awk -F'-' '{print $1}')
# NOTE: zfs must be after kernel was installed (as 2 separate k sync!!!!)
zfs

# For webzfs
libsodium-devel libffi-devel python3-devel

# For sanoid/syncoid
perl-Config-IniFiles perl-Data-Dumper perl-Capture-Tiny perl-Getopt-Long lzop mbuffer mhash pv

# For building aseprite from source
cmake ninja-build
libxcb-devel libX11-devel libXcursor-devel libXi-devel libXrandr-devel
libX11-devel libXext-devel libXcursor-devel libXi-devel libglvnd-devel fontconfig-devel pixman-devel

kopia kopia-ui
'''
