[development]
rebuild_before_running = true
enable_rebuild_indicator = true

[workspace]
paths = ["$HOME/projects", "$HOME/personal", "$HOME/Documents", "$HOME/"]
terminal = { width = 284, height = 86 }

[memories]
path = "$HOME/personal/grimoire/memories/"

[system]
rpms_path = "$HOME/rpms"

copr = '''
scottames/ghostty
yorickpeterse/stylua
quadratech188/vicinae
ilyaz/LACT
g3tchoo/prismlauncher
'''

packages = '''
keepassxc
git
stow
delta
nix
dnf-command(versionlock)
zsh
oh-my-posh
keychain
fzf
zoxide
ghostty
eza
gcc clang lld mold gdb lldb nasm clangd cppcheck valgrind
tmux
tree-sitter-cli
fastfetch
find
fd
golang gopls golang-mvdan-gofumpt golangci-lint gosec staticcheck goose
rg
krita gimp inkscape
drawio-x86_64-30.0.4.rpm # For vault hunters
bat
bc
btop
dua
unrar
sqlite
unzip
gitleaks
hyperfine # For benchmarking
vesktop-1.6.5.x86_64.rpm
qdbus
loupe
chromium
stylua
caddy
etckeeper
vicinae
rustup cargo
python3-pip
pnpm nodejs
java-openjdk-headless java-25-openjdk-devel
filezilla
jq
kate
gh
libreoffice
yt-dlp mpv vlc
xlsclients xwininfo
nodejs-bash-language-server
fuse-libs # For AppImages to work
openrgb
kdelibs-webkit
qdirstat # WizTree for linux
tokei
piper # Uses ratbagd under the hood
pipewire-codec-aptx # Bluetooth codec, probably not needed but why not (oh, this was already installed)
obs-studio-plugin-vkcapture
PureRef-2.1.3_x64.rpm
podman-compose
jellyfin
nss-tools
# opensnitch-1.8.0-1.x86_64.rpm opensnitch-ui-1.8.0-1.noarch.rpm
# Portmaster-2.1.19-1.x86_64.rpm
entr
chafa
kitten # Fix fastfetch not rendering images properly inside tmux
dig
minisign
inotify-tools # inotifywait and inotifywatch
imhex-1.38.1-Fedora-43-x86_64.rpm
gnome-clocks
uctags-2026.06.05-1.fc44.x86_64.rpm # C document symbols kinda I think
vivaldi-stable-8.0.4033.46-1.x86_64.rpm
pipewire-module-roc
pavucontrol

# Gaming
steam lutris Heroic-2.22.0-linux-x86_64.rpm
mangohud gamemode gamescope
r2modman-3.2.17.x86_64.rpm # Valheim mods launcher
wine winetricks protontricks
prismlauncher # Minecraft

# AMD Control/Monitoring tools
corectrl lact radeontop amdgpu_top-0.11.5-1.x86_64.rpm

# ZFS
@RAW https://zfsonlinux.org/fedora/zfs-release-3-1$(rpm --eval "%{dist}").noarch.rpm
@RAW kernel-devel-$(uname -r | awk -F'-' '{print $1}')
# NOTE: zfs must be after kernel was installed (as 2 separate k sync!!!!)
zfs

# For webzfs
libsodium-devel libffi-devel python3-devel

# For sanoid/syncoid
perl-Config-IniFiles perl-Data-Dumper perl-Capture-Tiny perl-Getopt-Long lzop mbuffer mhash pv

# For building aseprite from source
cmake ninja-build
libxcb-devel libX11-devel libXcursor-devel libXi-devel libXrandr-devel
libX11-devel libXext-devel libXcursor-devel libXi-devel libglvnd-devel fontconfig-devel pixman-devel

# Virtual Machine
qemu-kvm libvirt virt-manager

kopia kopia-ui

'''
