node.rules = [
    {
        matches = [
            { application.process.binary = "obs" }
            { application.name = "OBS Studio" }
        ]
        actions = {
            update-props = {
                node.virtual = true
            }
        }
    }
]
