InlayHints:
  BlockEnd: false
  Designators: true
  Enabled: true
  ParameterNames: false
  DeducedTypes: true
  DefaultArguments: true
  TypeNameLimit: 24
Diagnostics:
  Suppress: "*"
Index:
  StandardLibrary: false
CompileFlags:
  Add: [-x, c]
