#!/usr/bin/env bash

sess=$1
dir=$2

if [ "$dir" = "$HOME" ]; then
  tmux rename-window -t $sess:1 main
  tmux send-keys -t $sess:main.1 "fastfetch" C-m

  tmux new-window -t $sess -n dotfiles -c $HOME/dotfiles
  tmux send-keys -t $sess:dotfiles.1 "vim" C-m

  tmux new-window -t $sess -n diary -c $HOME/personal/dairy
  tmux send-keys -t $sess:diary.1 "vim" C-m

  tmux select-window -t $sess:main
elif [[ "$sess" == "ratry" || "$sess" == "kiwen-prototype" ]]; then
  tmux rename-window -t $sess:1 editor
  tmux send-keys -t $sess:editor.1 "nix develop" C-m
  tmux send-keys -t $sess:editor.1 "nvim" C-m

  tmux new-window -t $sess -n game -c $dir
  tmux send-keys -t $sess:game.1 "nix develop" C-m

  tmux select-window -t $sess:editor
elif [ "$sess" = "eko" ]; then
  tmux rename-window -t $sess:1 editor
  tmux send-keys -t $sess:editor.1 "vim" C-m

  tmux new-window -t $sess -n app -c $dir
  tmux split-window -t $sess:app.1 -v -c $dir
  tmux send-keys -t $sess:app.2 "watchexec --exts=go './reload.sh'" C-m
  tmux resize-pane -Z -t $sess:app.1

  tmux new-window -t $sess -n logs -c $dir
  tmux split-window -t $sess:logs.1 -h -c $dir
  tmux split-window -t $sess:logs.2 -v -c $dir
  tmux send-keys -t $sess:logs.1 "tail -f messages.log" C-m
  tmux send-keys -t $sess:logs.2 "tail -f client.log" C-m
  tmux send-keys -t $sess:logs.3 "go run ./cmd/server --stdout" C-m

  tmux select-window -t $sess:editor
elif [ "$sess" = "server" ]; then
  tmux rename-window -t $sess:1 local

  tmux new-window -t $sess -n remote -c $dir
  tmux send-keys -t $sess:remote.1 "ssh root@kyren.codes" C-m

  tmux new-window -t $sess -n editor -c $dir
  tmux send-keys -t $sess:editor.1 "vim" C-m

  tmux select-window -t $sess:remote
elif [[ "$dir" == "$HOME/projects/"* ]]; then
  tmux rename-window -t $sess:1 editor
  tmux send-keys -t $sess:editor.1 "vim" C-m
fi
