return {
    'kylechui/nvim-surround',
    version = '*',
    keys = {
        { 'ys' },
        { 'yss' },
        { 'S' },
        { 'cs' },
        { 'ds' },
        { '(', '<Plug>(nvim-surround-visual)(', mode = 'v' },
        { ')', '<Plug>(nvim-surround-visual))', mode = 'v' },
        { '{', '<Plug>(nvim-surround-visual){', mode = 'v' },
        { '}', '<Plug>(nvim-surround-visual)}', mode = 'v' },
        { '[', '<Plug>(nvim-surround-visual)[', mode = 'v' },
        { ']', '<Plug>(nvim-surround-visual)]', mode = 'v' },
        { '`', '<Plug>(nvim-surround-visual)`', mode = 'v' },
        { '"', '<Plug>(nvim-surround-visual)"', mode = 'v' },
        { "'", "<Plug>(nvim-surround-visual)'", mode = 'v' },
    },
    opts = {},
}
